# These users will be created into all servers
# All users with state: present will be created and state absent will be deleted
company_admin_list:
  - name: "Akshit Singhal"
    username: "AkshitS"
    keys:
      active:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8gOdvYe12yaVQGMZXgn0qcd7vxMZhj1wsBTDFP/HnwdnbywbV/jt//yGex51cTkfqoP3YlkdgUfQeKJws4j7rxu04gx6uRBIlRcR+7wdcFgks...................................."
      disabled:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsPoDM21LjBodcS3Kiq7ZDyNjFY4L03Yx2nSoSzdV7TKj00Zk8gh1hSSgI/xSDXiK+QEbfPuh/7+G3sfeDDN................................................................"
    shell: "/bin/bash"
    state: present
  - name: "Example Person"
    username: "ExamplePerson"
    state: absent

# This is the admin group where we will add users with sudo access
admin_group: infra_admin
